### ISSUE TITLE
Upgrade to Stackdriver Kubernetes Engine Monitoring aka v2(beta) Stackdriver for GKE

### ISSUE THREAD

**Issue by jmound** [GoogleCloudPlatform/pci-gke-blueprint#64]
The project is currently using Legacy Stackdriver. (See [Which Stackdriver support does my cluster use?](https://cloud.google.com/monitoring/kubernetes-engine/installing#kind-of-support) )

More precisely, GKE data is visible in Stackdriver's Legacy Kubernetes [dashboard](https://app.google.stackdriver.com/gke) as a result of Stackdriver Monitoring being set to Enabled ) ( and not v2(beta) ). Stackdriver Logging is disabled due to the `fluentd` customizations in place (centralized logging, and DLP API filtering).

In order to upgrade to "Stackdriver Kubernetes Engine Monitoring," the [recommended](https://cloud.google.com/monitoring/kubernetes-engine/installing#upgrade-instructions) method is to enable both Stackdriver Monitoring _and_ Stackdriver Logging, in order to choose "Enabled v2(beta)". This is undesirable because that will then cause the stock `fluentd` to be installed, which would then cause logs to go direct to Stackdriver Logs and bypass the DLP API filter. 

The most viable option is to package the v2(beta) configurations, and customize them as needed, while leaving the stock GKE Monitoring and Logging settings disabled.

**Comment by zealsomani** [comment]
2/25 Decisions
- use a centralized log sink
- use DLP scrubbing on the log sink to scrub the logs

**Comment by jmound** [comment]
As of #95, this project is using Stackdriver for GKE, the [default via terraform](https://www.terraform.io/docs/providers/google/r/container_cluster.html#logging_service).

Centralized logging + DLP scrubbing will be addressed in separate issues.
