### ISSUE TITLE
Configure Tiller to use TLS Auth

### ISSUE THREAD

**Issue by bgeesaman** [GoogleCloudPlatform/pci-gke-blueprint#74]
The instructions at https://github.com/GoogleCloudPlatform/terraform-pci-starter/blob/master/README.md#helm-installation-and-setup will most likely want to be modified to follow the guidance here: https://helm.sh/docs/using_helm/#using-ssl-between-helm-and-tiller to better protect the Tiller gRPC endpoint from malicious pods being able to access Tiller directly and install a privileged chart.

/cc @binamov

**Comment by jmound** [comment]
v2 of this project uses helm v3, which removes tiller entirely.
