### ISSUE TITLE
Terraform 0.12 support

### ISSUE THREAD

**Issue by anners** [GoogleCloudPlatform/pci-gke-blueprint#92]
When running ./_helpers/build-infra.sh I get:

Downloading modules/core_project_factory for project_network.project-factory...
Downloading terraform-google-modules/network/google 0.6.0 for vpc_pci...
- vpc_pci in .terraform/modules/vpc_pci/terraform-google-modules-terraform-google-network-1d3242b

Error: Module not found

The module address "modules/gsuite_group" could not be resolved.

If you intended this as a path relative to the current module, use
"./modules/gsuite_group" instead. The "./" prefix indicates that the address
is a relative filesystem path.

I am using terraform 0.12

I looks like it is related to https://github.com/terraform-google-modules/terraform-google-project-factory/issues/214

**Comment by morgante** [comment]
Updating to the latest version of network + project factory should help.

**Comment by jmound** [comment]
v2, just released, uses terraform v0.12
